### ISSUE TITLE
`handle': undefined method `each' 

### ISSUE THREAD

**Issue by jcmartins** [nohtyp/sensu-influxdb#4]
{"timestamp":"2015-02-25T14:27:31.357033+0000","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/metrics/influxdb-metrics.rb","name":"loadmetrics"},"output":"/etc/sensu/handlers/metrics/influxdb-metrics.rb:27:in `handle': undefined method `each' for #<String:0x00000002747fa0> (NoMethodError)\n"}

{"timestamp":"2015-02-25T14:27:31.475759+0000","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/metrics/influxdb-metrics.rb","name":"loadmetrics"},"output":"\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:55:in `block in <class:Handler>'\n"}

**Comment by nohtyp** [comment]
Can you see if "each_line" instead of each would work? I think that has changed between sensu versions.

**Comment by jcmartins** [comment]
tks!

Now it's ok.

**Comment by nohtyp** [comment]
cool..I will update the change
